[build]
  command = "npm i @rollup/rollup-linux-x64-gnu @esbuild/linux-x64 && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22.2.0"
  NPM_VERSION = "10.7.0"
  ROLLUP_SKIP_NODE_RESOLUTION = "true" 